<a href="https://colab.research.google.com/github/mbrady4/DS-Unit-1-Sprint-2-Data-Wrangling/blob/master/DS_Unit_1_Sprint_Challenge_2_Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Unit 1 Sprint Challenge 2

## Data Wrangling

In this Sprint Challenge you will use data from [Gapminder](https://www.gapminder.org/about-gapminder/), a Swedish non-profit co-founded by Hans Rosling. "Gapminder produces free teaching resources making the world understandable based on reliable statistics."
- [Cell phones (total), by country and year](https://raw.githubusercontent.com/open-numbers/ddf--gapminder--systema_globalis/master/ddf--datapoints--cell_phones_total--by--geo--time.csv)
- [Population (total), by country and year](https://raw.githubusercontent.com/open-numbers/ddf--gapminder--systema_globalis/master/ddf--datapoints--population_total--by--geo--time.csv)
- [Geo country codes](https://github.com/open-numbers/ddf--gapminder--systema_globalis/blob/master/ddf--entities--geo--country.csv)

These two links have everything you need to successfully complete the Sprint Challenge!
- [Pandas documentation: Working with Text Data](https://pandas.pydata.org/pandas-docs/stable/text.html]) (one question)
- [Pandas Cheat Sheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf) (everything else)

## Part 0. Load data

You don't need to add or change anything here. Just run this cell and it loads the data for you, into three dataframes.

In [0]:
import pandas as pd

cell_phones = pd.read_csv('https://raw.githubusercontent.com/open-numbers/ddf--gapminder--systema_globalis/master/ddf--datapoints--cell_phones_total--by--geo--time.csv')

population = pd.read_csv('https://raw.githubusercontent.com/open-numbers/ddf--gapminder--systema_globalis/master/ddf--datapoints--population_total--by--geo--time.csv')

geo_country_codes = (pd.read_csv('https://raw.githubusercontent.com/open-numbers/ddf--gapminder--systema_globalis/master/ddf--entities--geo--country.csv')
                       .rename(columns={'country': 'geo', 'name': 'country'}))

In [0]:
import numpy as np

In [62]:
cell_phones.shape, population.shape, geo_country_codes.shape

((9215, 3), (59297, 3), (273, 33))

In [63]:
cell_phones.head()

geo  time  cell_phones_total
0  abw  1960                0.0
1  abw  1965                0.0
2  abw  1970                0.0
3  abw  1975                0.0
4  abw  1976                0.0

In [64]:
population.head(5)

geo  time  population_total
0  afg  1800           3280000
1  afg  1801           3280000
2  afg  1802           3280000
3  afg  1803           3280000
4  afg  1804           3280000

In [65]:
geo_country_codes.head()

geo alt_5                    alternative_1 alternative_2 alternative_3  \
0  abkh   NaN                              NaN           NaN           NaN   
1   abw   NaN                              NaN           NaN           NaN   
2   afg   NaN  Islamic Republic of Afghanistan           NaN           NaN   
3   ago   NaN                              NaN           NaN           NaN   
4   aia   NaN                              NaN           NaN           NaN   

  alternative_4_cdiac arb1 arb2 arb3 arb4         ...          latitude  \
0                 NaN  NaN  NaN  NaN  NaN         ...               nan   
1               Aruba  NaN  NaN  NaN  NaN         ...              12.5   
2         Afghanistan  NaN  NaN  NaN  NaN         ...              33.0   
3              Angola  NaN  NaN  NaN  NaN         ...             -12.5   
4                 NaN  NaN  NaN  NaN  NaN         ...          18.21667   

  longitude main_religion_2008      country        pandg un_state  \
0       nan                NaN     Abkhazia          NaN    False   
1 -69.96667          christian        Aruba          NaN    False   
2      66.0             muslim  Afghanistan  AFGHANISTAN     True   
3      18.5          christian       Angola       ANGOLA     True   
4    -63.05          christian     Anguilla          NaN    False   

  unicode_region_subtag  upper_case_name world_4region        world_6region  
0                   NaN              NaN        europe  europe_central_asia  
1                    AW            ARUBA      americas              america  
2                    AF      AFGHANISTAN          asia           south_asia  
3                    AO           ANGOLA        africa   sub_saharan_africa  
4                    AI         ANGUILLA      americas              america  

[5 rows x 33 columns]

## Part 1. Join data

First, join the `cell_phones` and `population` dataframes (with an inner join on `geo` and `time`).

The resulting dataframe's shape should be: (8590, 4)

In [66]:
merged = pd.merge(cell_phones, population, how='inner', on=['geo', 'time'])
merged.shape

(8590, 4)

Then, select the `geo` and `country` columns from the `geo_country_codes` dataframe, and join with your population and cell phone data.

The resulting dataframe's shape should be: (8590, 5)

In [67]:
merged = pd.merge(merged, geo_country_codes[ ['geo', 'country'] ], on='geo')
merged.shape

(8590, 5)

In [68]:
merged.head()

geo  time  cell_phones_total  population_total      country
0  afg  1960                0.0           8996351  Afghanistan
1  afg  1965                0.0           9938414  Afghanistan
2  afg  1970                0.0          11126123  Afghanistan
3  afg  1975                0.0          12590286  Afghanistan
4  afg  1976                0.0          12840299  Afghanistan

## Part 2. Make features

Calculate the number of cell phones per person, and add this column onto your dataframe.

(You've calculated correctly if you get 1.220 cell phones per person in the United States in 2017.)

In [0]:
merged['cell_phones_per_person'] = (merged['cell_phones_total'] / merged['population_total'])

In [70]:
merged.head()

geo  time  cell_phones_total  population_total      country  \
0  afg  1960                0.0           8996351  Afghanistan   
1  afg  1965                0.0           9938414  Afghanistan   
2  afg  1970                0.0          11126123  Afghanistan   
3  afg  1975                0.0          12590286  Afghanistan   
4  afg  1976                0.0          12840299  Afghanistan   

   cell_phones_per_person  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     0.0

In [71]:
merged[ (merged['country'] == 'United States') & (merged['time'] == 2017) ]

geo  time  cell_phones_total  population_total        country  \
8134  usa  2017      395,881,000.0         324459463  United States   

      cell_phones_per_person  
8134      1.2201246847283354

Modify the `geo` column to make the geo codes uppercase instead of lowercase.

In [0]:
merged['geo'] = [ x.upper() for x in merged['geo'] ]

In [73]:
merged.head()

geo  time  cell_phones_total  population_total      country  \
0  AFG  1960                0.0           8996351  Afghanistan   
1  AFG  1965                0.0           9938414  Afghanistan   
2  AFG  1970                0.0          11126123  Afghanistan   
3  AFG  1975                0.0          12590286  Afghanistan   
4  AFG  1976                0.0          12840299  Afghanistan   

   cell_phones_per_person  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     0.0

## Part 3. Process data

Use the describe function, to describe your dataframe's numeric columns, and then its non-numeric columns.

(You'll see the time period ranges from 1960 to 2017, and there are 195 unique countries represented.)

In [74]:
#Describe Numeric Columns
merged.describe()

time    cell_phones_total     population_total  \
count             8,590.0              8,590.0              8,590.0   
mean  1,994.1934807916182  9,004,949.642905472 29,838,230.581722934   
std    14.257974607310302 55,734,084.872179635 116,128,377.47477299   
min               1,960.0                  0.0              4,433.0   
25%               1,983.0                  0.0          1,456,148.0   
50%               1,995.0              6,200.0          5,725,062.5   
75%               2,006.0          1,697,652.0         18,105,812.0   
max               2,017.0      1,474,097,000.0      1,409,517,397.0   

       cell_phones_per_person  
count                 8,590.0  
mean       0.2796385558059151  
std         0.454246656214052  
min                       0.0  
25%                       0.0  
50%     0.0015636266438163813  
75%        0.4611491855201403  
max         2.490242818521353

In [75]:
#Describe Non-Numeric Columns
merged.describe(exclude='number')

geo  country
count   8590     8590
unique   195      195
top      URY  Senegal
freq      46       46

In 2017, what were the top 5 countries with the most cell phones total?

Your list of countries should have these totals:

| country | cell phones total |
|:-------:|:-----------------:|
|    ?    |     1,474,097,000 |
|    ?    |     1,168,902,277 |
|    ?    |       458,923,202 |
|    ?    |       395,881,000 |
|    ?    |       236,488,548 |



In [0]:
# This optional code formats float numbers with comma separators
pd.options.display.float_format = '{:,}'.format

In [85]:
merged.groupby('country')['cell_phones_total'].aggregate(np.max).sort_values(ascending=False)[:5]

country
China           1,474,097,000.0
India           1,168,902,277.0
Indonesia         458,923,202.0
United States     395,881,000.0
Brazil            280,728,796.0
Name: cell_phones_total, dtype: float64

My fifth population total differs from the table, thus I did the below groupby to ensure verify that my table was pulling from 2017 totals. 

In [80]:
merged.groupby('country', as_index=False).aggregate(np.max).sort_values(by=['time', 'cell_phones_total', 'country'], ascending=False)[:5]

country  geo  time  cell_phones_total  population_total  \
35           China  CHN  2017    1,474,097,000.0        1409517397   
76           India  IND  2017    1,168,902,277.0        1339180127   
77       Indonesia  IDN  2017      458,923,202.0         263991379   
186  United States  USA  2017      395,881,000.0         324459463   
23          Brazil  BRA  2017      280,728,796.0         209288278   

     cell_phones_per_person  
35       1.0458168186766978  
76       0.8728491809526382  
77        1.738402230172827  
186       1.228758722948959  
23       1.3746853195773652

2017 was the first year that China had more cell phones than people.

What was the first year that the USA had more cell phones than people?

In [78]:
merged[ merged['country'] == 'United States' ]

geo  time  cell_phones_total  population_total        country  \
8092  USA  1960                0.0         186808228  United States   
8093  USA  1965                0.0         199815540  United States   
8094  USA  1970                0.0         209588150  United States   
8095  USA  1975                0.0         219205296  United States   
8096  USA  1976                0.0         221239215  United States   
8097  USA  1977                0.0         223324042  United States   
8098  USA  1978                0.0         225449657  United States   
8099  USA  1979                0.0         227599878  United States   
8100  USA  1980                0.0         229763052  United States   
8101  USA  1984           91,600.0         238573861  United States   
8102  USA  1985          340,213.0         240824120  United States   
8103  USA  1986          681,825.0         243098935  United States   
8104  USA  1987        1,230,855.0         245402864  United States   
8105  USA  1988        2,069,441.0         247739582  United States   
8106  USA  1989        3,508,944.0         250113187  United States   
8107  USA  1990        5,283,055.0         252529950  United States   
8108  USA  1991        7,557,148.0         254974819  United States   
8109  USA  1992       11,032,753.0         257454273  United States   
8110  USA  1993       16,009,461.0         260020186  United States   
8111  USA  1994       24,134,421.0         262741566  United States   
8112  USA  1995       33,785,661.0         265658849  United States   
8113  USA  1996       44,042,992.0         268803424  United States   
8114  USA  1997       55,312,293.0         272136551  United States   
8115  USA  1998       69,209,321.0         275542603  United States   
8116  USA  1999       86,047,003.0         278862277  United States   
8117  USA  2000      109,478,031.0         281982778  United States   
8118  USA  2001      128,500,000.0         284852391  United States   
8119  USA  2002      141,800,000.0         287506847  United States   
8120  USA  2003      160,637,000.0         290027624  United States   
8121  USA  2004      184,819,000.0         292539324  United States   
8122  USA  2005      203,700,000.0         295129501  United States   
8123  USA  2006      229,600,000.0         297827356  United States   
8124  USA  2007      249,300,000.0         300595175  United States   
8125  USA  2008      261,300,000.0         303374067  United States   
8126  USA  2009      274,283,000.0         306076362  United States   
8127  USA  2010      285,118,000.0         308641391  United States   
8128  USA  2011      297,404,000.0         311051373  United States   
8129  USA  2012      304,838,000.0         313335423  United States   
8130  USA  2013      310,698,000.0         315536676  United States   
8131  USA  2014      355,500,000.0         317718779  United States   
8132  USA  2015      382,307,000.0         319929162  United States   
8133  USA  2016      395,881,000.0         322179605  United States   
8134  USA  2017      395,881,000.0         324459463  United States   

      cell_phones_per_person  
8092                     0.0  
8093                     0.0  
8094                     0.0  
8095                     0.0  
8096                     0.0  
8097                     0.0  
8098                     0.0  
8099                     0.0  
8100                     0.0  
8101   0.0003839481811462992  
8102   0.0014127031793991398  
8103   0.0028047222831313516  
8104    0.005015650510093476  
8105    0.008353291723887707  
8106     0.01402942420624947  
8107     0.02092050863669834  
8108     0.02963880131237587  
8109    0.042853252624010636  
8110     0.06157006979450434  
8111     0.09185612070227213  
8112     0.12717687036278622  
8113     0.16384832955104026  
8114     0.20325198065731348  
8115     0.25117466499363805  
8116     0.30856451408807795  
8117      0.3882436784845066  
8118     0.45111083515532086  
8119      0.4

2014 was the first year that the United States had more cell phones than people. 

## Part 4. Reshape data

Create a pivot table:
- Columns: Years 2007—2017
- Rows: China, India, United States, Indonesia, Brazil (order doesn't matter)
- Values: Cell Phones Total

The table's shape should be: (5, 11)

In [112]:
merged.head()

geo  time  cell_phones_total  population_total      country  \
0  AFG  1960                0.0           8996351  Afghanistan   
1  AFG  1965                0.0           9938414  Afghanistan   
2  AFG  1970                0.0          11126123  Afghanistan   
3  AFG  1975                0.0          12590286  Afghanistan   
4  AFG  1976                0.0          12840299  Afghanistan   

   cell_phones_per_person  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     0.0

In [123]:
countries = ['China', 'United States', 'Indonesia', 'Brazil']
time = merged[ merged['time'] > 2006]

def in_countries(x):
  if str(x) in countries:
    return True
  else:
    return False

subset = (merged[( (merged['country'] == 'United States') |
                   (merged['country'] == 'China') |
                   (merged['country'] == 'India') |
                   (merged['country'] == 'Indonesia') |
                   (merged['country'] == 'Brazil') ) &
                   (merged['time'] > 2006)
               ])

merged_pivot = subset.pivot(columns='time', index='country', values='cell_phones_total')
merged_pivot

time                   2007          2008          2009          2010  \
country                                                                 
Brazil        120,980,103.0 150,641,403.0 169,385,584.0 196,929,978.0   
China         547,306,000.0 641,245,000.0 747,214,000.0 859,003,000.0   
India         233,620,000.0 346,890,000.0 525,090,000.0 752,190,000.0   
Indonesia      93,386,881.0 140,578,243.0 163,676,961.0 211,290,235.0   
United States 249,300,000.0 261,300,000.0 274,283,000.0 285,118,000.0   

time                   2011            2012            2013            2014  \
country                                                                       
Brazil        234,357,507.0   248,323,703.0   271,099,799.0   280,728,796.0   
China         986,253,000.0 1,112,155,000.0 1,229,113,000.0 1,286,093,000.0   
India         893,862,478.0   864,720,917.0   886,304,245.0   944,008,677.0   
Indonesia     249,805,619.0   281,963,665.0   313,226,914.0   325,582,819.0   
United States 297,404,000.0   304,838,000.0   310,698,000.0   355,500,000.0   

time                     2015            2016            2017  
country                                                        
Brazil          257,814,274.0   244,067,356.0   236,488,548.0  
China         1,291,984,200.0 1,364,934,000.0 1,474,097,000.0  
India         1,001,056,000.0 1,127,809,000.0 1,168,902,277.0  
Indonesia       338,948,340.0   385,573,398.0   458,923,202.0  
United States   382,307,000.0   395,881,000.0   395,881,000.0

In [124]:
merged_pivot.shape

(5, 11)

#### OPTIONAL BONUS QUESTION!

Sort these 5 countries, by biggest increase in cell phones from 2007 to 2017.

Which country had 935,282,277 more cell phones in 2017 versus 2007?

In [125]:
merged_pivot.head()

time                   2007          2008          2009          2010  \
country                                                                 
Brazil        120,980,103.0 150,641,403.0 169,385,584.0 196,929,978.0   
China         547,306,000.0 641,245,000.0 747,214,000.0 859,003,000.0   
India         233,620,000.0 346,890,000.0 525,090,000.0 752,190,000.0   
Indonesia      93,386,881.0 140,578,243.0 163,676,961.0 211,290,235.0   
United States 249,300,000.0 261,300,000.0 274,283,000.0 285,118,000.0   

time                   2011            2012            2013            2014  \
country                                                                       
Brazil        234,357,507.0   248,323,703.0   271,099,799.0   280,728,796.0   
China         986,253,000.0 1,112,155,000.0 1,229,113,000.0 1,286,093,000.0   
India         893,862,478.0   864,720,917.0   886,304,245.0   944,008,677.0   
Indonesia     249,805,619.0   281,963,665.0   313,226,914.0   325,582,819.0   
United States 297,404,000.0   304,838,000.0   310,698,000.0   355,500,000.0   

time                     2015            2016            2017  
country                                                        
Brazil          257,814,274.0   244,067,356.0   236,488,548.0  
China         1,291,984,200.0 1,364,934,000.0 1,474,097,000.0  
India         1,001,056,000.0 1,127,809,000.0 1,168,902,277.0  
Indonesia       338,948,340.0   385,573,398.0   458,923,202.0  
United States   382,307,000.0   395,881,000.0   395,881,000.0

In [128]:
( merged_pivot[2017] - merged_pivot[2007]).sort_values(ascending=False)

country
India           935,282,277.0
China           926,791,000.0
Indonesia       365,536,321.0
United States   146,581,000.0
Brazil          115,508,445.0
dtype: float64

India had the biggest increase in cell phones from 2007 to 2017, with a net addition of 935,282,277 cell phones.

If you have the time and curiosity, what other questions can you ask and answer with this data?